########################################################################

# avec sudo ansible-playbook -c local config.vm3-6.yml
---
- hosts: localhost
  tasks:
    - shell: while ip route del default; do true;done
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth1"
      ignore_errors: True
    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip4 172.16.2.186/28
