tun46d : main.o iftun.o extremite.o
	gcc -o tun46d main.o iftun.o extremite.o

main.o :
	gcc -o main.o -c main.c

iftun.o :
	gcc -o iftun.o -c iftun.c

extremite.o :
	gcc -o extremite.o -c extremite.c

clean :
	rm main.o
	rm iftun.o
	rm extremite.o
	rm tun46d
