########################################################################

# avec sudo ansible-playbook -c local config.vm2-6.yml
---
- hosts: localhost
  tasks:
    - shell: while ip route del default; do true;done
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth1"
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth2"
      ignore_errors: True
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip6 fc00:1234:1::26/64 
    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:2::26/64 
    - sysctl: name="net.ipv6.conf.all.forwarding=1" value=1 sysctl_set=yes state=present reload=yes

