########################################################################

# avec sudo ansible-playbook -c local config.vm2-6.yml
---
- hosts: localhost
  tasks:
    - copy: src="resolv.conf" dest="/etc/resolv.conf" owner=root group=root mode=644
    - apt: name=radvd state=latest
    - shell: while ip route del default; do true;done
    - shell: nmcli connection del "Connexion filaire 1"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth1"
      ignore_errors: True
    - shell: nmcli connection del "Connexion filaire 2"
      ignore_errors: True
    - shell: nmcli connection del "ansible-eth2"
      ignore_errors: True
    - shell: nmcli connection add ifname eth1 con-name ansible-eth1 type ethernet ip6 fc00:1234:1::26/64
    - shell: nmcli connection add ifname eth2 con-name ansible-eth2 type ethernet ip6 fc00:1234:2::26/64
    - sysctl: name="net.ipv6.conf.all.forwarding=1" value=1 sysctl_set=yes state=present reload=yes
    - copy: src="radvd.conf" dest="/etc/radvd.conf" owner=root group=root mode=644
    - service: name=radvd state=started
    - service: name=radvd state=stopped
    - service: name=radvd state=started
